model_path: "examples/FeedForward/"

# tokenizer:
#   type: "bpe"
#   params:
#     vocab_size: 20000
#     min_frequency: 2

vectorizer:
  type: "tf-idf"
  params:
    max_features: 1000
    stop_words: "english"
    norm: "l2"
    use_idf: true
    smooth_idf: true
    sublinear_tf: false

model:
  type: "feedforward"
  params:
    input_dim: 1000
    # hidden_dims: [128, 128, 128, 128]
    hidden_dims: [512, 512, 512, 512, 512]
    output_dim: 5
    # dropout_rate: 0.1
    lr: 0.0001
    # scheduler: true
    device: "cuda"

