model_path: "examples/FeedForward/"

# tokenizer:
#   type: "bpe"
#   params:
#     vocab_size: 20000
#     min_frequency: 2

vectorizer:
  type: "tf-idf"
  params:
    max_features: 10000
    stop_words: "english"
    norm: "l2"
    use_idf: true
    smooth_idf: true
    sublinear_tf: false

model:
  type: "feedforward"
  params:
    input_dim: 10000
    hidden_dims: [512, 256]
    output_dim: 5
    dropout_rate: 0.3
    lr: 0.001
    # scheduler: true
    device: "cuda"

