model_path: "examples/LogisticRegression/"

vectorizer:
  type: "tf-idf"
  params:
    max_features: 10000
    stop_words: "english"
    # ngram_range: [1, 2]
    norm: "l2"
    use_idf: true
    smooth_idf: true
    sublinear_tf: false

model:
  type: "logistic-regression"
  params:
    C: 1.0
    max_iter: 200
    penalty: "l2"
    solver: "lbfgs"
