model_path: "examples/Rnn/"

vectorizer:
  type: "tf-idf"
  params:
    max_features: 1000  # This is fine
    stop_words: "english"
    norm: "l2"
    use_idf: true
    smooth_idf: true

model:
  type: "rnn"
  params:
    input_dim: 1000
    hidden_dims: 64
    output_dim: 5
    dropout_rate: 0.3
    lr: 0.0001
    batch_size: 300
    max_epochs: 20
    patience: 3
    scheduler: true 
    device: "cuda"